language: ruby
rvm:
- 2.3.0
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
addons:
  ssh_known_hosts: 159.203.216.201
before_install:
  - bash _scripts/install.sh
script:
  - bash _scripts/build.sh
  - bash _scripts/test.sh
after_success:
  - bash _scripts/deploy.sh

# - eval "$(ssh-agent -s)" #start the ssh agent
# - chmod 600 _deploy/netp_wiki_deploy # this key should have push access
# - ssh-add _deploy/netp_wiki_deploy
# - git remote add deploy DEPLOY_REPO_URI_GOES_HERE
# - git push deploy
