# Site Settings
title: 'NetP Wiki'
company: 'ShadowLink'
email: 'ShadowLinkIT@protonmail.com'
github_url: 'https://github.com/ckreon/netp_wiki'
description: 'A collection of open-source guides focusing on network privacy & security.'

# Build Settings
permalink: /:title/

include:
  - _guides

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - vendor
  - gulpfile.js
  - node_modules
  - package.json
  - makepdf.js

gems:
  - jekyll-assets
  - octopress-minify-html
  - jekyll-sitemap

# Asset Settings
assets:
  sources:
    - _assets/pdf
    - _assets/icons

# Style Settings
sass:
  sass_dir: '_assets/css'
  style: 'compressed'

# Markdown Settings
markdown: 'redcarpet'
redcarpet:
  extensions:
    - no_intra_emphasis
    - tables
    - autolink
    - strikethrough
    - with_toc_data