# Site Settings
title: NetP Wiki
company: ShadowLink IT
email: ShadowLinkIT@protonmail.com
github_url: https://github.com/ckreon/netp_wiki
description: 'A collection of open-source guides focusing on Network Privacy & Security.'
url: ''
baseurl: '' # the subpath of your site, e.g. /blog

# Build Settings
include: ['_pages']
exclude: ['README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor', 'gulpfile.js', 'node_modules', 'package.json']
gems: ['jekyll-assets', 'octopress-minify-html', 'jekyll-sitemap']

# FrontMatter Settings
permalink: '/:title/'

# Style Settings
sass:
  sass_dir: '_dev/scss'
  style: 'compressed'

# Markdown Settings
markdown: 'redcarpet'
redcarpet:
  extensions: ['no_intra_emphasis', 'tables', 'autolink', 'strikethrough', 'with_toc_data']