# Site Settings
title: 'NetP Wiki'
description: 'A collection of open-source guides focusing on network privacy & security.'

# Site Variables
company: 'ShadowLink'
email: 'ShadowLinkIT@protonmail.com'
github_url: 'https://github.com/ckreon/ww-netp_wiki'


# Build Settings
permalink: /:title/

include:
  - _guides

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - vendor
  - gulpfile.js
  - node_modules
  - package.json

gems:
  - jekyll-assets
  - octopress-minify-html
  - jekyll-sitemap

# Asset Settings
assets:
  sources:
    - _assets/pdf
    - _assets/icons

# Markdown Settings
markdown: 'redcarpet'
redcarpet:
  extensions:
    - no_intra_emphasis
    - tables
    - autolink
    - strikethrough
    - with_toc_data