# Site Settings
title: NetP Wiki
email: ckreon@gmail.com
github_username: ckreon
description: 'A collection of open-source guides focusing on Network Privacy & Security.'
url: 'http://159.203.247.147'
baseurl: '' # the subpath of your site, e.g. /blog

# Build Settings
include: ['_pages']
exclude: ['README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor', 'gulpfile.js', 'node_modules', 'package.json']
gems: ['jekyll-assets', 'jekyll-sitemap']
minify_html: 'true'

# FrontMatter Settings
permalink: '/:title/'

# Style Settings
sass:
  sass_dir: '_dev/scss'
  style: 'compressed'

# Markdown Settings
markdown: 'redcarpet'
redcarpet:
  extensions: ['no_intra_emphasis', 'tables', 'autolink', 'strikethrough', 'with_toc_data']